<?php
include_once '../../../include/cp_header.php';
require_once XOOPS_ROOT_PATH . '/modules/xcform/include/functions.php';
xcform_admin_boot(); xoops_cp_header(); xcform_admin_register_css();
if(class_exists('Xmf\\Module\\Admin')) \Xmf\Module\Admin::getInstance()->displayNavigation('form_edit.php');
$db=$GLOBALS['xoopsDB']; $tbl=$db->prefix('xcform_forms');
$form_id=isset($_REQUEST['id'])?(int)$_REQUEST['id']:0; $is_edit=$form_id>0;
$form=['form_id'=>0,'name'=>'','slug'=>'','description'=>'','fields'=>'[]','settings'=>'{}','is_active'=>1];
if($is_edit){$found=xcform_get_form($form_id);if(!$found){redirect_header('forms.php',2,_AM_XCFORM_FORM_NOT_FOUND);exit;}$form=$found;}
if(isset($_POST['op'])&&$_POST['op']==='save'){
    $name=$db->escape(trim($_POST['form_name']??''));
    $slug=$db->escape(preg_replace('/[^a-z0-9\-]/','',strtolower(trim($_POST['form_slug']??''))));
    $desc=$db->escape(trim($_POST['form_desc']??''));
    $is_active=isset($_POST['is_active'])?1:0;
    $fd=json_decode($_POST['fields_json']??'[]',true); if(!is_array($fd))$fd=[];
    $fj=$db->escape(json_encode($fd,JSON_UNESCAPED_UNICODE));
    $st=$db->escape(json_encode(['success_msg'=>trim($_POST['success_msg']??'Formunuz başarıyla gönderildi. Teşekkürler!'),'notify_email'=>trim($_POST['notify_email']??''),'email_subject'=>trim($_POST['email_subject']??'Yeni Form Gönderisi'),'enable_captcha'=>isset($_POST['enable_captcha'])?1:0],JSON_UNESCAPED_UNICODE));
    $now=time();
    if($is_edit) $db->queryF("UPDATE {$tbl} SET name='{$name}',slug='{$slug}',description='{$desc}',fields='{$fj}',settings='{$st}',is_active='{$is_active}' WHERE form_id='{$form_id}'");
    else $db->queryF("INSERT INTO {$tbl}(name,slug,description,fields,settings,is_active,created_at)VALUES('{$name}','{$slug}','{$desc}','{$fj}','{$st}','{$is_active}','{$now}')");
    redirect_header('forms.php',2,_AM_XCFORM_FORM_SAVED); exit;
}
$settings=json_decode($form['settings']??'{}',true)?:[];
global $xoopsTpl;
$d=XOOPS_ROOT_PATH.'/modules/xcform/templates/admin/';
if(method_exists($xoopsTpl,'addTemplateDir')) $xoopsTpl->addTemplateDir($d);
if(isset($GLOBALS['xoopsSecurity'])) $xoopsTpl->assign('xoops_token_html',$GLOBALS['xoopsSecurity']->getTokenHTML());
$xoopsTpl->assign('xoops_url',XOOPS_URL); $xoopsTpl->assign('module_url',XOOPS_URL.'/modules/xcform/');
$xoopsTpl->assign('form',$form); $xoopsTpl->assign('settings',$settings); $xoopsTpl->assign('is_edit',$is_edit);
// Builder lang vars
$xoopsTpl->assign('xcf_lang_edit_title',   _AM_XCFORM_BUILDER_EDIT_TITLE);
$xoopsTpl->assign('xcf_lang_new_title',    _AM_XCFORM_BUILDER_NEW_TITLE);
$xoopsTpl->assign('xcf_lang_tab_builder',  _AM_XCFORM_BUILDER_TAB_BUILDER);
$xoopsTpl->assign('xcf_lang_tab_settings', _AM_XCFORM_BUILDER_TAB_SETTINGS);
$xoopsTpl->assign('xcf_lang_field_types',  _AM_XCFORM_BUILDER_FIELD_TYPES);
$xoopsTpl->assign('xcf_lang_drag_hint',    _AM_XCFORM_BUILDER_DRAG_HINT);
$xoopsTpl->assign('xcf_lang_save_form',    _AM_XCFORM_BUILDER_SAVE_FORM);
$xoopsTpl->assign('xcf_lang_isp_title',    _AM_XCFORM_BUILDER_ISP_TITLE);
$xoopsTpl->assign('xcf_lang_confirm_del',  _AM_XCFORM_BUILDER_CONFIRM_DEL);
$xoopsTpl->assign('xcf_lang_required_lbl', _AM_XCFORM_BUILDER_REQUIRED_LBL);
$xoopsTpl->assign('xcf_lang_isp_content',        _AM_XCFORM_ISP_CONTENT);
$xoopsTpl->assign('xcf_lang_isp_field_label',     _AM_XCFORM_ISP_FIELD_LABEL);
$xoopsTpl->assign('xcf_lang_isp_field_name',      _AM_XCFORM_ISP_FIELD_NAME);
$xoopsTpl->assign('xcf_lang_isp_placeholder',     _AM_XCFORM_ISP_PLACEHOLDER);
$xoopsTpl->assign('xcf_lang_isp_default_val',     _AM_XCFORM_ISP_DEFAULT_VAL);
$xoopsTpl->assign('xcf_lang_isp_options',         _AM_XCFORM_ISP_OPTIONS);
$xoopsTpl->assign('xcf_lang_isp_required',        _AM_XCFORM_ISP_REQUIRED);
$xoopsTpl->assign('xcf_lang_isp_desc',            _AM_XCFORM_ISP_DESC);
$xoopsTpl->assign('xcf_lang_isp_width',           _AM_XCFORM_ISP_WIDTH);
$xoopsTpl->assign('xcf_lang_isp_width_full',      _AM_XCFORM_ISP_WIDTH_FULL);
$xoopsTpl->assign('xcf_lang_isp_save',            _AM_XCFORM_ISP_SAVE);
$xoopsTpl->assign('xcf_lang_isp_settings_suffix', _AM_XCFORM_ISP_SETTINGS_SUFFIX);
$xoopsTpl->assign('xcf_lang_isp_default_option',  _AM_XCFORM_ISP_DEFAULT_OPTION);
$xoopsTpl->assign('xcf_lang_isp_default_option2', _AM_XCFORM_ISP_DEFAULT_OPTION2);
$xoopsTpl->assign('xcf_lang_ft_short_text',   _AM_XCFORM_FT_SHORT_TEXT);
$xoopsTpl->assign('xcf_lang_ft_long_text',    _AM_XCFORM_FT_LONG_TEXT);
$xoopsTpl->assign('xcf_lang_ft_email',        _AM_XCFORM_FT_EMAIL);
$xoopsTpl->assign('xcf_lang_ft_website',      _AM_XCFORM_FT_WEBSITE);
$xoopsTpl->assign('xcf_lang_ft_phone',        _AM_XCFORM_FT_PHONE);
$xoopsTpl->assign('xcf_lang_ft_number',       _AM_XCFORM_FT_NUMBER);
$xoopsTpl->assign('xcf_lang_ft_date',         _AM_XCFORM_FT_DATE);
$xoopsTpl->assign('xcf_lang_ft_time',         _AM_XCFORM_FT_TIME);
$xoopsTpl->assign('xcf_lang_ft_file',         _AM_XCFORM_FT_FILE);
$xoopsTpl->assign('xcf_lang_ft_hidden',       _AM_XCFORM_FT_HIDDEN);
$xoopsTpl->assign('xcf_lang_ft_label',        _AM_XCFORM_FT_LABEL);
$xoopsTpl->assign('xcf_lang_ft_heading',      _AM_XCFORM_FT_HEADING);
$xoopsTpl->assign('xcf_lang_ft_paragraph',    _AM_XCFORM_FT_PARAGRAPH);
$xoopsTpl->assign('xcf_lang_ft_choice',       _AM_XCFORM_FT_CHOICE);
$xoopsTpl->assign('xcf_lang_ft_image_choice', _AM_XCFORM_FT_IMAGE_CHOICE);
$xoopsTpl->assign('xcf_lang_ft_dropdown',     _AM_XCFORM_FT_DROPDOWN);
$xoopsTpl->assign('xcf_lang_ft_consent',      _AM_XCFORM_FT_CONSENT);
$xoopsTpl->assign('xcf_lang_ft_signature',    _AM_XCFORM_FT_SIGNATURE);
$xoopsTpl->assign('xcf_lang_set_form_name',        _AM_XCFORM_SET_FORM_NAME);
$xoopsTpl->assign('xcf_lang_set_form_slug',        _AM_XCFORM_SET_FORM_SLUG);
$xoopsTpl->assign('xcf_lang_set_slug_hint',        _AM_XCFORM_SET_SLUG_HINT);
$xoopsTpl->assign('xcf_lang_set_slug_placeholder', _AM_XCFORM_SET_SLUG_PLACEHOLDER);
$xoopsTpl->assign('xcf_lang_set_desc',             _AM_XCFORM_SET_DESC);
$xoopsTpl->assign('xcf_lang_set_success_msg',      _AM_XCFORM_SET_SUCCESS_MSG);
$xoopsTpl->assign('xcf_lang_set_default_success',  _AM_XCFORM_SET_DEFAULT_SUCCESS);
$xoopsTpl->assign('xcf_lang_set_notify_email',     _AM_XCFORM_SET_NOTIFY_EMAIL);
$xoopsTpl->assign('xcf_lang_set_email_hint',       _AM_XCFORM_SET_EMAIL_HINT);
$xoopsTpl->assign('xcf_lang_set_email_subject',    _AM_XCFORM_SET_EMAIL_SUBJECT);
$xoopsTpl->assign('xcf_lang_set_default_subject',  _AM_XCFORM_SET_DEFAULT_SUBJECT);
$xoopsTpl->assign('xcf_lang_set_is_active',        _AM_XCFORM_SET_IS_ACTIVE);
$xoopsTpl->assign('xcf_lang_set_captcha',          _AM_XCFORM_SET_CAPTCHA);
$xoopsTpl->assign('xcf_lang_save',                 _AM_XCFORM_SAVE);
xcform_admin_assign_lang('forms'); // status labels, actions vb. ortak değişkenler
echo $xoopsTpl->fetch($d.'xcform_admin_form_edit.tpl');
xoops_cp_footer();